INSERT INTO company.addresses (address_id, text, town_id) VALUES (1, '108 Lakeside Court', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (2, '1343 Prospect St', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (3, '1648 Eastgate Lane', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (4, '2284 Azalea Avenue', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (5, '2947 Vine Lane', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (6, '3067 Maya', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (7, '3197 Thornhill Place', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (8, '3284 S. Blank Avenue', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (9, '332 Laguna Niguel', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (10, '3454 Bel Air Drive', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (11, '3670 All Ways Drive', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (12, '3708 Montana', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (13, '3711 Rollingwood Dr', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (14, '3919 Pinto Road', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (15, '4311 Clay Rd', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (16, '4777 Rockne Drive', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (17, '5678 Clear Court', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (18, '5863 Sierra', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (19, '6058 Hill Street', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (20, '6118 Grasswood Circle', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (21, '620 Woodside Ct.', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (22, '6307 Greenbelt Way', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (23, '6448 Castle Court', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (24, '6774 Bonanza', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (25, '6968 Wren Ave.', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (26, '7221 Peachwillow Street', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (27, '7270 Pepper Way', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (28, '7396 Stratton Circle', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (29, '7808 Brown St.', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (30, '7902 Grammercy Lane', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (31, '8668 Via Neruda', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (32, '8684 Military East', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (33, '8751 Norse Drive', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (34, '9320 Teakwood Dr.', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (35, '9435 Breck Court', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (36, '9745 Bonita Ct.', 5);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (37, 'Pascalstr 951', 31);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (38, '94, rue Descartes', 30);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (39, '1226 Shoe St.', 8);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (40, '1399 Firestone Drive', 8);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (41, '1902 Santa Cruz', 8);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (42, '1970 Napa Ct.', 8);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (43, '250 Race Court', 8);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (44, '5672 Hale Dr.', 8);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (45, '5747 Shirley Drive', 8);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (46, '6387 Scenic Avenue', 8);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (47, '6872 Thornwood Dr.', 8);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (48, '7484 Roundtree Drive', 8);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (49, '8157 W. Book', 8);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (50, '9539 Glenside Dr', 8);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (51, '9833 Mt. Dias Blv.', 8);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (52, '10203 Acorn Avenue', 2);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (53, '3997 Via De Luna', 23);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (54, 'Downshire Way', 23);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (55, '1411 Ranch Drive', 15);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (56, '3074 Arbor Drive', 15);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (57, '390 Ridgewood Ct.', 15);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (58, '9666 Northridge Ct.', 15);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (59, '9752 Jeanne Circle', 15);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (60, '8154 Via Mexico', 27);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (61, '80 Sunview Terrace', 26);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (62, '1825 Corte Del Prado', 17);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (63, '2598 La Vista Circle', 17);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (64, '3421 Bouncing Road', 17);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (65, '3977 Central Avenue', 17);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (66, '5086 Nottingham Place', 17);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (67, '5379 Treasure Island Way', 17);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (68, '8209 Green View Court', 17);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (69, '8463 Vista Avenue', 17);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (70, '9693 Mellowood Street', 17);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (71, '991 Vista Verde', 17);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (72, '1061 Buskrik Avenue', 3);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (73, '172 Turning Dr.', 3);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (74, '2038 Encino Drive', 3);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (75, '2046 Las Palmas', 3);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (76, '2059 Clay Rd', 3);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (77, '207 Berry Court', 3);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (78, '2080 Sycamore Drive', 3);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (79, '2466 Clearland Circle', 3);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (80, '2687 Ridge Road', 3);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (81, '2812 Mazatlan', 3);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (82, '3026 Anchor Drive', 3);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (83, '3281 Hillview Dr.', 3);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (84, '3632 Bank Way', 3);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (85, '371 Apple Dr.', 3);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (86, '504 O St.', 3);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (87, '5423 Champion Rd.', 3);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (88, '6057 Hill Street', 3);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (89, '6870 D Bel Air Drive', 3);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (90, '7338 Green St.', 3);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (91, '7511 Cooper Dr.', 3);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (92, '8152 Claudia Dr.', 3);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (93, '8411 Mt. Orange Place', 3);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (94, '9277 Country View Lane', 3);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (95, '9784 Mt Etna Drive', 3);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (96, '9825 Coralie Drive', 3);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (97, '1185 Dallas Drive', 7);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (98, '1362 Somerset Place', 7);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (99, '181 Gaining Drive', 7);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (100, '1962 Cotton Ct.', 7);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (101, '2176 Apollo Way', 7);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (102, '2294 West 39th St.', 7);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (103, '3238 Laguna Circle', 7);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (104, '3385 Crestview Drive', 7);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (105, '3665 Oak Creek Ct.', 7);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (106, '3928 San Francisco', 7);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (107, '475 Santa Maria', 7);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (108, '5242 Marvelle Ln.', 7);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (109, '5452 Corte Gilberto', 7);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (110, '6629 Polson Circle', 7);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (111, '7640 First Ave.', 7);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (112, '7883 Missing Canyon Court', 7);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (113, '8624 Pepper Way', 7);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (114, '9241 St George Dr.', 7);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (115, '213 Stonewood Drive', 18);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (116, '2425 Notre Dame Ave', 18);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (117, '3884 Beauty Street', 18);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (118, '8036 Summit View Dr.', 18);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (119, '9605 Pheasant Circle', 18);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (120, '1245 Clay Road', 10);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (121, '1748 Bird Drive', 10);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (122, '310 Winter Lane', 10);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (123, '3127 El Camino Drive', 10);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (124, '3514 Sunshine', 10);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (125, '1144 Paradise Ct.', 6);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (126, '1921 Ranch Road', 6);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (127, '3333 Madhatter Circle', 6);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (128, '342 San Simeon', 6);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (129, '3848 East 39th Street', 6);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (130, '5256 Chickpea Ct.', 6);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (131, '5979 El Pueblo', 6);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (132, '6580 Poor Ridge Court', 6);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (133, '7435 Ricardo', 6);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (134, '7691 Benedict Ct.', 6);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (135, '7772 Golden Meadow', 6);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (136, '8585 Los Gatos Ct.', 6);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (137, '9314 Icicle Way', 6);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (138, '9530 Vine Lane', 6);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (139, '989 Crown Ct', 6);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (140, '25 95th Ave NE', 20);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (141, '4095 Cooper Dr.', 20);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (142, '4155 Working Drive', 20);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (143, '463 H Stagecoach Rd.', 20);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (144, '5050 Mt. Wilson Way', 20);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (145, '5203 Virginia Lane', 20);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (146, '5458 Gladstone Drive', 20);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (147, '5553 Cash Avenue', 20);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (148, '5669 Ironwood Way', 20);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (149, '6697 Ridge Park Drive', 20);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (150, '7048 Laurel', 20);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (151, '8192 Seagull Court', 20);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (152, '350 Pastel Drive', 22);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (153, '34 Waterloo Road', 21);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (154, '8291 Crossbow Way', 28);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (155, '5678 Lakeview Blvd.', 24);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (156, '1356 Grove Way', 12);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (157, '158 Walnut Ave', 12);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (158, '1792 Belmont Rd.', 12);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (159, '2275 Valley Blvd.', 12);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (160, '3747 W. Landing Avenue', 12);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (161, '3841 Silver Oaks Place', 12);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (162, '4566 La Jolla', 12);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (163, '4734 Sycamore Court', 12);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (164, '5030 Blue Ridge Dr.', 12);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (165, '5734 Ashford Court', 12);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (166, '7726 Driftwood Drive', 12);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (167, '8310 Ridge Circle', 12);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (168, '896 Southdale', 12);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (169, '9652 Los Angeles', 12);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (170, '2487 Riverside Drive', 19);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (171, '1397 Paradise Ct.', 14);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (172, '1400 Gate Drive', 14);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (173, '3030 Blackburn Ct.', 14);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (174, '4350 Minute Dr.', 14);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (175, '8967 Hamilton Ave.', 14);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (176, '9297 Kenston Dr.', 14);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (177, '9687 Shakespeare Drive', 14);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (178, '9100 Sheppard Avenue North', 29);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (179, '636 Vine Hill Way', 25);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (180, '101 Candy Rd.', 1);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (181, '1275 West Street', 1);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (182, '2137 Birchwood Dr', 1);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (183, '2383 Pepper Drive', 1);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (184, '2427 Notre Dame Ave.', 1);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (185, '2482 Buckingham Dr.', 1);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (186, '3066 Wallace Dr.', 1);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (187, '3397 Rancho View Drive', 1);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (188, '3768 Door Way', 1);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (189, '4909 Poco Lane', 1);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (190, '6369 Ellis Street', 1);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (191, '6891 Ham Drive', 1);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (192, '7297 RisingView', 1);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (193, '8000 Crane Court', 1);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (194, '8040 Hill Ct', 1);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (195, '8467 Clifford Court', 1);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (196, '9006 Woodside Way', 1);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (197, '9322 Driving Drive', 1);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (198, '9863 Ridge Place', 1);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (199, '9882 Clay Rde', 1);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (200, '9906 Oak Grove Road', 1);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (201, '1378 String Dr', 13);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (202, '1803 Olive Hill', 13);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (203, '2176 Brown Street', 13);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (204, '2266 Greenwood Circle', 13);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (205, '2598 Breck Court', 13);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (206, '2736 Scramble Rd', 13);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (207, '4312 Cambridge Drive', 13);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (208, '5009 Orange Street', 13);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (209, '5670 Bel Air Dr.', 13);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (210, '5980 Icicle Circle', 13);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (211, '6510 Hacienda Drive', 13);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (212, '6937 E. 42nd Street', 13);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (213, '7165 Brock Lane', 13);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (214, '7559 Worth Ct.', 13);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (215, '7985 Center Street', 13);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (216, '9495 Limewood Place', 13);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (217, '9533 Working Drive', 13);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (218, '177 11th Ave', 16);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (219, '1962 Ferndale Lane', 16);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (220, '2473 Orchard Way', 16);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (221, '4096 San Remo', 16);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (222, '4310 Kenston Dr.', 16);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (223, '4444 Pepper Way', 16);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (224, '4525 Benedict Ct.', 16);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (225, '5263 Etcheverry Dr', 16);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (226, '535 Greendell Pl', 16);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (227, '6871 Thornwood Dr.', 16);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (228, '6951 Harmony Way', 16);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (229, '7086 O St.', 16);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (230, '7145 Matchstick Drive', 16);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (231, '7820 Bird Drive', 16);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (232, '7939 Bayview Court', 16);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (233, '8316 La Salle St.', 16);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (234, '9104 Mt. Sequoia Ct.', 16);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (235, '1234 Seaside Way', 9);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (236, '5725 Glaze Drive', 9);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (237, '1064 Slow Creek Road', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (238, '1102 Ravenwood', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (239, '1220 Bradford Way', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (240, '1349 Steven Way', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (241, '136 Balboa Court', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (242, '137 Mazatlan', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (243, '1398 Yorba Linda', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (244, '1619 Stillman Court', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (245, '2144 San Rafael', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (246, '2354 Frame Ln.', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (247, '2639 Anchor Court', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (248, '3029 Pastime Dr', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (249, '3243 Buckingham Dr.', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (250, '426 San Rafael', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (251, '4598 Manila Avenue', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (252, '4948 West 4th St', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (253, '502 Alexander Pl.', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (254, '5025 Holiday Hills', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (255, '5125 Cotton Ct.', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (256, '5375 Clearland Circle', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (257, '5376 Catanzaro Way', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (258, '5407 Cougar Way', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (259, '5666 Hazelnut Lane', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (260, '5802 Ampersand Drive', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (261, '6498 Mining Rd.', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (262, '6578 Woodhaven Ln.', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (263, '6657 Sand Pointe Lane', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (264, '6843 San Simeon Dr.', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (265, '7126 Ending Ct.', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (266, '7127 Los Gatos Court', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (267, '7166 Brock Lane', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (268, '7403 N. Broadway', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (269, '7439 Laguna Niguel', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (270, '7594 Alexander Pl.', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (271, '7616 Honey Court', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (272, '77 Birchwood', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (273, '7765 Sunsine Drive', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (274, '7842 Ygnacio Valley Road', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (275, '8290 Margaret Ct.', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (276, '8656 Lakespring Place', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (277, '874 Olivera Road', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (278, '931 Corte De Luna', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (279, '9537 Ridgewood Drive', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (280, '9964 North Ridge Drive', 4);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (281, '1285 Greenbrier Street', 11);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (282, '2115 Passing', 11);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (283, '2601 Cambridge Drive', 11);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (284, '3114 Notre Dame Ave.', 11);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (285, '3280 Pheasant Circle', 11);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (286, '4231 Spar Court', 11);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (287, '4852 Chaparral Court', 11);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (288, '5724 Victory Lane', 11);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (289, '591 Merriewood Drive', 11);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (290, '7230 Vine Maple Street', 11);
INSERT INTO company.addresses (address_id, text, town_id) VALUES (291, '163 Nishava Str, ent A, apt. 1', 32);
