INSERT INTO company.departments (department_id, name, manager_id) VALUES (1, 'Engineering', 12);
INSERT INTO company.departments (department_id, name, manager_id) VALUES (2, 'Tool Design', 4);
INSERT INTO company.departments (department_id, name, manager_id) VALUES (3, 'Sales', 273);
INSERT INTO company.departments (department_id, name, manager_id) VALUES (4, 'Marketing', 46);
INSERT INTO company.departments (department_id, name, manager_id) VALUES (5, 'Purchasing', 6);
INSERT INTO company.departments (department_id, name, manager_id) VALUES (6, 'Research and Development', 42);
INSERT INTO company.departments (department_id, name, manager_id) VALUES (7, 'Production', 148);
INSERT INTO company.departments (department_id, name, manager_id) VALUES (8, 'Production Control', 21);
INSERT INTO company.departments (department_id, name, manager_id) VALUES (9, 'Human Resources', 30);
INSERT INTO company.departments (department_id, name, manager_id) VALUES (10, 'Finance', 3);
INSERT INTO company.departments (department_id, name, manager_id) VALUES (11, 'Information Services', 42);
INSERT INTO company.departments (department_id, name, manager_id) VALUES (12, 'Document Control', 90);
INSERT INTO company.departments (department_id, name, manager_id) VALUES (13, 'Quality Assurance', 274);
INSERT INTO company.departments (department_id, name, manager_id) VALUES (14, 'Facilities and Maintenance', 218);
INSERT INTO company.departments (department_id, name, manager_id) VALUES (15, 'Shipping and Receiving', 85);
INSERT INTO company.departments (department_id, name, manager_id) VALUES (16, 'Executive', 109);
