INSERT INTO company.towns (town_id, name) VALUES (1, 'Redmond');
INSERT INTO company.towns (town_id, name) VALUES (2, 'Calgary');
INSERT INTO company.towns (town_id, name) VALUES (3, 'Edmonds');
INSERT INTO company.towns (town_id, name) VALUES (4, 'Seattle');
INSERT INTO company.towns (town_id, name) VALUES (5, 'Bellevue');
INSERT INTO company.towns (town_id, name) VALUES (6, 'Issaquah');
INSERT INTO company.towns (town_id, name) VALUES (7, 'Everett');
INSERT INTO company.towns (town_id, name) VALUES (8, 'Bothell');
INSERT INTO company.towns (town_id, name) VALUES (9, 'San Francisco');
INSERT INTO company.towns (town_id, name) VALUES (10, 'Index');
INSERT INTO company.towns (town_id, name) VALUES (11, 'Snohomish');
INSERT INTO company.towns (town_id, name) VALUES (12, 'Monroe');
INSERT INTO company.towns (town_id, name) VALUES (13, 'Renton');
INSERT INTO company.towns (town_id, name) VALUES (14, 'Newport Hills');
INSERT INTO company.towns (town_id, name) VALUES (15, 'Carnation');
INSERT INTO company.towns (town_id, name) VALUES (16, 'Sammamish');
INSERT INTO company.towns (town_id, name) VALUES (17, 'Duvall');
INSERT INTO company.towns (town_id, name) VALUES (18, 'Gold Bar');
INSERT INTO company.towns (town_id, name) VALUES (19, 'Nevada');
INSERT INTO company.towns (town_id, name) VALUES (20, 'Kenmore');
INSERT INTO company.towns (town_id, name) VALUES (21, 'Melbourne');
INSERT INTO company.towns (town_id, name) VALUES (22, 'Kent');
INSERT INTO company.towns (town_id, name) VALUES (23, 'Cambridge');
INSERT INTO company.towns (town_id, name) VALUES (24, 'Minneapolis');
INSERT INTO company.towns (town_id, name) VALUES (25, 'Portland');
INSERT INTO company.towns (town_id, name) VALUES (26, 'Duluth');
INSERT INTO company.towns (town_id, name) VALUES (27, 'Detroit');
INSERT INTO company.towns (town_id, name) VALUES (28, 'Memphis');
INSERT INTO company.towns (town_id, name) VALUES (29, 'Ottawa');
INSERT INTO company.towns (town_id, name) VALUES (30, 'Bordeaux');
INSERT INTO company.towns (town_id, name) VALUES (31, 'Berlin');
INSERT INTO company.towns (town_id, name) VALUES (32, 'Sofia');
